In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [7]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [8]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [10]:
(df[['Insulin', 'Glucose']] == 0).sum()

Insulin    374
Glucose      5
dtype: int64

In [30]:
df_clean = df[df['Insulin'] != 0]
df_clean

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
13,1,189,60,23,846,30.1,0.398,59,1
...,...,...,...,...,...,...,...,...,...
753,0,181,88,44,510,43.3,0.222,26,1
755,1,128,88,39,110,36.5,1.057,37,1
760,2,88,58,26,16,28.4,0.766,22,0
763,10,101,76,48,180,32.9,0.171,63,0
765,5,121,72,23,112,26.2,0.245,30,0

In [31]:
df_clean['Insulin'].corr(df_clean['Glucose'])

np.float64(0.5800099317152834)

In [33]:
df_clean.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.201487,0.213740,0.095997,0.082171,-0.011282,-0.000402,0.680920,0.258846
Glucose,0.201487,1.000000,0.203356,0.203526,0.580010,0.208711,0.140409,0.346041,0.512201
BloodPressure,0.213740,0.203356,1.000000,0.232342,0.098272,0.301530,-0.020834,0.299845,0.192819
SkinThickness,0.095997,0.203526,0.232342,1.000000,0.184888,0.653425,0.154056,0.170694,0.257854
Insulin,0.082171,0.580010,0.098272,0.184888,1.000000,0.228328,0.130395,0.220261,0.303454
BMI,-0.011282,0.208711,0.301530,0.653425,0.228328,1.000000,0.112954,0.080778,0.271796
DiabetesPedigreeFunction,-0.000402,0.140409,-0.020834,0.154056,0.130395,0.112954,1.000000,0.076609,0.200759
Age,0.680920,0.346041,0.299845,0.170694,0.220261,0.080778,0.076609,1.000000,0.352982
Outcome,0.258846,0.512201,0.192819,0.257854,0.303454,0.271796,0.200759,0.352982,1.000000

In [34]:
import statsmodels.api as sm

X = df[['Glucose', 'BMI', 'Age', 'Insulin']]
X = sm.add_constant(X)
y = df['Outcome']

modelo = sm.Logit(y, X).fit()
print(modelo.summary())

Optimization terminated successfully.
         Current function value: 0.490871
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  768
Model:                          Logit   Df Residuals:                      763
Method:                           MLE   Df Model:                            4
Date:                Mon, 22 Dec 2025   Pseudo R-squ.:                  0.2411
Time:                        03:56:38   Log-Likelihood:                -376.99
converged:                       True   LL-Null:                       -496.74
Covariance Type:            nonrobust   LLR p-value:                 1.185e-50
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -8.5207      0.678    -12.576      0.000      -9.849      -7.193
Glucose        0.0340      0.004      9.572      0.000       0.027       0.041
BMI            0.0841      0.014      6.120      0.000       0.057       0.111
Age            0.0286      0.008      3.707      0.000       0.013       0.044
Insulin       -0.0010      0.001     -1.312      0.189      -0.003       0.001
==============================================================================

In [35]:
# el modelo explica el 24% de probabilidad mediante el r¨2, además si aplicamos el odds ratio a
#l coeficiente de la glucose podemos observar OR=e0.034≈1.035, este resultado explica que aumenta la probabilidad
# de tener diabetes en un 3.3% al consumir glucose, tambien otros valores como el BMI con su coeficiente aumenta en un 8.8% sobre
#quienes tienen glucosa y cada año adicional de edad aumenta el riesgo en ~2.9%

In [36]:
from scipy.stats import ttest_ind

grupo0 = df[df['Outcome'] == 0]['Glucose']
grupo1 = df[df['Outcome'] == 1]['Glucose']

ttest_ind(grupo0, grupo1, equal_var=False)

TtestResult(statistic=np.float64(-13.751537067396413), pvalue=np.float64(2.6441613495403223e-36), df=np.float64(461.33165635340805))

In [ ]:
#Se rechaza hipotesis nula de igualdad con la prueba T student extremadamente fuerte, con la t:-13.75
#lo que indica que las personas con màs diabetes tienen mayor glucosa