In [31]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [32]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [40]:
df = pd.read_csv('/content/drive/MyDrive/Cars_Multi555.csv')

In [41]:
df

,car_name,model,origin,mpg,cylinders,displacement,horsepower,weight,acceleration
0,chevrolet chevelle malibu,70,1,18.0,8,307.0,130,3504,12.0
1,buick skylark 320,70,1,15.0,8,350.0,165,3693,11.5
2,plymouth satellite,70,1,18.0,8,318.0,150,3436,11.0
3,amc rebel sst,70,1,16.0,8,304.0,150,3433,12.0
4,ford torino,70,1,17.0,8,302.0,140,3449,10.5
...,...,...,...,...,...,...,...,...,...
393,ford mustang gl,82,1,27.0,4,140.0,86,2790,15.6
394,vw pickup,82,2,44.0,4,97.0,52,2130,24.6
395,dodge rampage,82,1,32.0,4,135.0,84,2295,11.6
396,ford ranger,82,1,28.0,4,120.0,79,2625,18.6
397,chevy s-10,82,1,31.0,4,119.0,82,2720,19.4

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   car_name      398 non-null    object
 1   model         398 non-null    int64
 2   origin        398 non-null    int64
 3   mpg           398 non-null    float64
 4   cylinders     398 non-null    int64
 5   displacement  398 non-null    float64
 6   horsepower    398 non-null    object
 7   weight        398 non-null    int64
 8   acceleration  398 non-null    float64
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [43]:
df.describe()

,model,origin,mpg,cylinders,displacement,weight,acceleration
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,76.010050,1.572864,23.514573,5.454774,193.425879,2970.424623,15.568090
std,3.697627,0.802055,7.815984,1.701004,104.269838,846.841774,2.757689
min,70.000000,1.000000,9.000000,3.000000,68.000000,1613.000000,8.000000
25%,73.000000,1.000000,17.500000,4.000000,104.250000,2223.750000,13.825000
50%,76.000000,1.000000,23.000000,4.000000,148.500000,2803.500000,15.500000
75%,79.000000,2.000000,29.000000,8.000000,262.000000,3608.000000,17.175000
max,82.000000,3.000000,46.600000,8.000000,455.000000,5140.000000,24.800000

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
#definicion de caracteristicas
X = df[['weight','cylinders','mpg','model']]
y = df ['acceleration']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

model.score(X_test, y_test)

0.34776482451232793

In [51]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=1000,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_score = rf_model.score(X_test, y_test)
print(rf_score)

0.44998914924194455

In [52]:
#este modelo de arboles de decisión no predice tan bien pero funciona para mi objetivo de aprendizaje
import ipywidgets as widgets
from IPython.display import display

In [65]:
# Widgets
weight_widget = widgets.FloatText(description='weight_', value=3504)
cylinders_widget = widgets.FloatText(description='cylinders_', value=8)
mpg_widget = widgets.FloatText(description='mpg_', value=18.0)
model_widget = widgets.FloatText(description='model_', value=70)

button = widgets.Button(description='Predict')
output = widgets.Output()

# Función del botón
def Pulsar_boton(b):
    with output:
        output.clear_output()

        weight_ = weight_widget.value
        cylinders_ = cylinders_widget.value
        mpg_ = mpg_widget.value
        model_year_ = model_widget.value

        input_data = pd.DataFrame(
            [[weight_, cylinders_, mpg_, model_year_]],
            columns=['weight', 'cylinders', 'mpg', 'model']
        )

        prediction = rf_model.predict(input_data)[0]
        print(f'La predicción es: {prediction:.2f}')

# Conectar botón
button.on_click(Pulsar_boton)

# boton
display(
    weight_widget,
    cylinders_widget,
    mpg_widget,
    model_widget,
    button,
    output
)

FloatText(value=3504.0, description='weight_')

FloatText(value=8.0, description='cylinders_')

FloatText(value=18.0, description='mpg_')

FloatText(value=70.0, description='model_')

Button(description='Predict', style=ButtonStyle())

Output()